# Vision Validation Plugin for Fabrikator
# AI-powered CAD geometry validation using Blender rendering and vision AI

plugin:
  name: Vision Validation
  slug: vision-validator
  author: Fabrikator Team
  description: |
    AI-powered visual validation of 3D CAD geometry.
    Renders 3MF files from multiple viewpoints using Blender and analyzes
    the geometry using GPT-4 Vision or Gemini to detect issues.
  tags:
    - validation
    - vision
    - ai
    - cad
    - quality
  iconUrl: https://fabrikator.ai/icons/vision-validate.png

requirements:
  apiKeys:
    - name: API_KEY
      description: API key for authenticating requests to the vision service
      required: true
      fallback: none
    - name: OPENAI_API_KEY
      description: OpenAI API key for GPT-4 Vision analysis
      required: false
      fallback: platform
    - name: GEMINI_API_KEY
      description: Google Gemini API key (alternative to OpenAI)
      required: false
      fallback: platform

capabilities:
  dataAccess:
    artifacts: true
    sessionState: true
    storagePrefix: sessions/${sessionId}/artifacts/

  prompts:
    agents:
      - agent: cad
        position: append
        priority: 60
        content: |
          ## VISION VALIDATION PLUGIN
          
          Use vision validation to verify your geometry is correct:
          
          ```
          call_plugin(
            pluginSlug="forge-plugins-vision",
            toolName="vision_validate",
            args={
              part: "part_headband",  // Full name as used in write_scad
              partDescription: "..."  // REQUIRED for single parts
            }
          )
          ```
          
          The plugin renders 5 views (ISO, Front, Right, Top, Bottom) and analyzes them.
          
          **How to write a good `partDescription`:**
          1. **Overall shape**: Basic form (e.g., "90-degree elbow pipe", "cylindrical body with flange")
          2. **Key features**: ALL geometric features present (e.g., "has external threading", "4 mounting holes")
          3. **Connectivity**: How parts connect (e.g., "bend smoothly connects both legs")
          4. **Hollow/internal**: Internal features (e.g., "hollow tube with 9mm inner diameter")
          5. **Relative positions**: Feature locations (e.g., "flange near the bend")
          
          **Example good partDescription:**
          `"90-degree elbow pipe where the bend smoothly connects both straight legs (no gaps). One leg is shorter and plain. The longer leg has external threading and a circular flange near the bend. The pipe is hollow throughout."`
          
          **IMPORTANT:**
          - Vision validation CANNOT verify dimensions - it cannot measure from images
          - You can validate hardware.scad to make sure that you've placed the hardware correctly relative to each other. You should also validate assembly_all to make sure the hardware is properly integrated within it.
          - Validate all parts individually BEFORE validating assembly and assembly_all.
          - If verdict is FAIL: fix the identified issues
          - If verdict is UNCERTAIN: add more specific checks or ignore the result if you're confident enough in your own assessment.
          - You can also use this tool to verify floating geometry, this is a common issue with SCAD files so be sure to check for it.
          - **CRITICAL** All created files must be validated with this plugin, if you change a file, remember to validate it again.

          CRITICAL RULES
          - **Validation verdicts**:
            * \`fail\` with **critical** issues → Must fix before proceeding
            * \`warn\` with minor issues → Fix if practical, but **do NOT over-iterate** on micro-features (like sub-millimeter chamfers) that may not be visible in renders
            * \`pass\` → Move on immediately
          - **When to STOP iterating**: If vision flags a feature you KNOW is in your code (e.g., "chamfer not visible" but your code has \`chamfer=0.5\`), the issue is likely render resolution, not your code. Accept the warning and move on.
          - **Always explore ALL library capabilities first**: review the preloaded library list and use available plugin tools to search documentation if needed.
          - **Prefer library functions over manual implementations**.
          - Prioritize geometric correctness before decorative details.
          - Respect geometric orientation when modeling connected parts.

          ## RENDER PREVIEW TOOL

          **CRITICAL** Prefer THIS TOOL over the vision_validate tool as you'll be able to see the images by yourself.
          
          Use render preview to get 300x300 images from standard views:
          
          ```
          call_plugin(
            pluginSlug="forge-plugins-vision",
            toolName="render_preview",
            args={
              part: "assembly_all",                // Used for naming outputs
              views: ["iso", "front", "right"]     // REQUIRED: one or more of iso, front, back, left, right, top, bottom
            }
          )
          ```
          
          The tool expects:
          - A direct `artifact3mfUrl` in context (same contract as vision_validate).
          - `views` must include at least one allowed view name (no defaults).
          
          It returns base64 JPEG artifacts named `<part>_<view>.jpg` and a summary listing rendered views.

  tools:
    - name: vision_validate
      description: |
        Validate the visual integrity of a 3D part or assembly using AI vision analysis.
        Renders 5 orthographic views and analyzes them for geometry issues.
      parameters:
        type: object
        properties:
          part:
            type: string
            description: The name of the SCAD part file (e.g., "base", "assembly"). REQUIRED.
          partDescription:
            type: string
            description: |
              Description of what this specific part should look like, its key features,
              and geometry. REQUIRED when validating a single part (not assembly).
          focus:
            type: string
            description: Optional free-form instructions describing what specific aspects to inspect.
          checks:
            type: array
            items:
              type: string
            description: Optional list of specific checklist items to validate.
        required:
          - part
        additionalProperties: false
      execution:
        type: docker
        config:
          image: ghcr.io/unforkableco/forge-plugins-vision:latest
          port: 8080
          endpoint: /validate
          timeout: 300000
          retries: 1
    - name: render_preview
      description: |
        Render one or more standard views (300x300) of a 3MF file and return the images.
        Requires a direct artifact3mfUrl (same contract as vision_validate).
      parameters:
        type: object
        properties:
          part:
            type: string
            description: Part or assembly name (used for naming outputs). REQUIRED.
          views:
            type: array
            items:
              type: string
              enum: [iso, front, back, left, right, top, bottom]
            description: |
              Required. One or more standard views to render.
              Allowed: iso, front, back, left, right, top, bottom.
        required:
          - part
          - views
        additionalProperties: false
      execution:
        type: docker
        config:
          image: ghcr.io/unforkableco/forge-plugins-vision:latest
          port: 8080
          endpoint: /render
          timeout: 180000
          retries: 1

pricing:
  model: free

