# Vision Validation Plugin for Fabrikator
# AI-powered CAD geometry validation using Blender rendering and vision AI

plugin:
  name: Vision Validation
  slug: vision-validator
  author: Fabrikator Team
  description: |
    AI-powered visual validation of 3D CAD geometry.
    Renders 3MF files from multiple viewpoints using Blender
  tags:
    # - validation
    - vision
    - ai
    - cad
    - quality
  iconUrl: https://fabrikator.ai/icons/vision-validate.png

  apiKeys:
    - name: RENDER_RESOLUTION
      description: Resolution for renders (e.g. 500)
      required: false
      fallback: "500"
    - name: RENDER_SAMPLES
      description: Number of render samples (e.g. 128)
      required: false
      fallback: "16"

capabilities:
  dataAccess:
    artifacts: true
    sessionState: true
    storagePrefix: sessions/${sessionId}/artifacts/

  executionDefaults:
    type: docker
    config:
      image: ghcr.io/unforkableco/forge-plugins-vision:latest
      port: 8080

  prompts:
    agents:
      - agent: cad
        position: append
        priority: 60
        content: |


          ## VISUAL VERIFICATION PROTOCOL
          
          **CRITICAL: DO NOT TRUST YOUR SCAD SCRIPTS BLINDLY.**
          Code that looks correct often produces unexpected geometry (intersections, gaps, misalignment) that is invisible in code but obvious in renders.

          ## CRITICAL: render_preview gives you IMAGES, not verdicts.
          The fact that render_preview returns "ok: true" means the RENDERING SUCCEEDED - 
          it says NOTHING about geometry correctness!
          
          **YOU MUST:**
          1.  Generate parts using `write_scad`.
          2.  **IMMEDIATELY** verify them visually using `render_preview`.
          3.  Inspect the returned images for defects, EVEN MINOR ISSUES COUNT.
          4.  **COMPARE AGAINST THE DESIGN IMAGE**: After every render, compare your result to the original design image provided at the start. Ask yourself:
              - Do ALL the features from the design image appear in my render?
              - Are the proportions matching the design?
              - Am I missing any small details or protrusions?
          5.  Iterate until the VISUAL result **MATCHES THE DESIGN IMAGE**, not just until it "looks okay".
          
          **Remember**: The design image is your target. Your renders should look like the design image. If they don't match, you must iterate and adjust until they do. This may require 5-10+ iterations.
          
          Use the `render_preview` tool to get rendered images from standard views:
          
          ```
          call_plugin(
            pluginSlug="forge-plugins-vision",
            toolName="render_preview",
            args={
              part: "assembly_all",                // Used for naming outputs
              views: ["iso", "front", "right"]     // REQUIRED: one or more of iso, front, back, left, right, top, bottom
            }
          )
          ```
          
          It returns base64 PNG artifacts named `<part>_<view>.png` which you will see in the chat history.
          **Analyze these images carefully AND COMPARE TO THE DESIGN IMAGE** before proceeding or marking a task as complete.
          ITS BETTER TO VALIDATE PARTS INDIVIDUALLY THAN ASSEMBLIES, AS ASSEMBLIES CAN HIDE ISSUES IN PARTS.

  tools:
    - name: render_preview
      description: |
        Render one or more standard views (at configured resolution) of a 3MF file and return the images.
        Requires a direct artifact3mfUrl (same contract as vision_validate).
      parameters:
        type: object
        properties:
          part:
            type: string
            description: Part or assembly name (used for naming outputs). REQUIRED.
          views:
            type: array
            items:
              type: string
              enum: [iso, front, back, left, right, top, bottom]
            description: |
              Required. One or more standard views to render.
              Allowed: iso, front, back, left, right, top, bottom.
        required:
          - part
          - views
        additionalProperties: false
      execution:
        config:
          endpoint: /render
          timeout: 180000
          retries: 1

pricing:
  model: free

